blank_issues_enabled: false
contact_links:
  - name: ğŸš¨Bug Report
    url: https://github.com/junsyun22/chatting-server/issues/new?template=bug_report.md
    about: ğŸ›Report a bug in the project.
  - name: âœ…Feature Request
    url: https://github.com/junsyun22/chatting-server/issues/new?template=feature_request.md
    about: Suggest a new feature for the project.
